VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

Private Sub Workbook_Open()

'    If Workbooks.Count <> 1 Then
'        If MsgBox("We detected another opened Excel File. This " & _
'                  "app will hide them temporarily, and will show again after " & _
'                  "you close it. Do you want to continue?", vbYesNo + vbInformation) = vbNo Then
'            ThisWorkbook.Close
'        End If
'    End If
'
'    MainForm.Show vbModeless

End Sub
